### PR TITLE
Refactor to ES6 - fix feedback

### PR DESCRIPTION
**Pull request by krocheck**
@yyy898 here's an update, sorry it took so long!  I think I implemented your changes appropriately, but I needed to refactor the module to ES6 to pull it off.  Please test these changes and let me know if you encounter any bugs.

### CODE REVIEW

**Comment by krocheck** [comment]
@yyy898 did you want to move forward with this?

**Comment by yyy898** [comment]
im sorry i totally forgot about this,
i get an error when i use your updated code:
image

**Comment by krocheck** [comment]
My bad ... just pushed a commit to the branch to fix that.

**Comment by yyy898** [comment]
your update seems good, i comitted your changes, thanks for the help

**Pull request merged**
